### PR TITLE
Small config changes necessary for prod deployment

### PR DESCRIPTION
**Pull request by hubertp-lshift**
- add CORS
- redirect stderr
- add additional modules for Jetty startup

### CODE REVIEW

**Comment by jsiembida** [comment]
GHCI test it

**Comment by jsiembida** [comment]
GHCI retest it

**Comment by jsiembida** [comment]
GHCI test it

**Comment by jsiembida** [comment]
GHCI test it

**Comment by jsiembida** [comment]
GHCI test it again

**Comment by jsiembida** [comment]
GHCI retest it

**Comment by hubertp-lshift** [comment]
@jsiembida anything missing?

**Comment by jsiembida** [comment]
No, LGTM.

**Comment by hubertp-lshift** [comment]
Yeah, it's fine. We cannot fix to a specific address since any app can actually call the service.

**Comment by hubertp-lshift** [comment]
@jsiembida button click, please?

**Pull request merged**
